# Generated by Django 3.2.4 on 2021-06-19 20:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 1, 58, 27, 854111)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_of_comment',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 1, 58, 27, 854111)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 1, 58, 27, 854111)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='item_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='auctions.category', verbose_name='Item Category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='previous_bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_bidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
